### ISSUE TITLE
代码部分不理解

### ISSUE THREAD

**Issue by hushengwang1999** [Dengyu-Wu/SNN-Regularisation-Cutoff#2]
There is a code issue. Isn't the CFS layer intended to replace the RELU activation function of ANN? Why are there two activation functions in the model?
![图片](https://user-images.githubusercontent.com/51084088/229352120-5486f1cb-6af2-44c9-b0e6-8a576272a35d.png)

**Comment by Dengyu-Wu** [comment]
Additional ReLU layers after CFS do not affect training, but are used for ANN-to-SNN conversion since SpKeras only recognizes ReLU layers.
